### ISSUE TITLE
Support for rain and wind gauge possible?

### ISSUE THREAD

**Issue by sweh** [karaktaka/grafana-netatmo#10]
Is support for rain and wind gauge possible?

**Comment by karaktaka** [comment]
I do have a dashboard with rain and wind gauge somewhere. Let me take a look if I can find it

**Comment by karaktaka** [comment]
Unfortunately I can not find the Version with wind and rain gauge and it also doesn't seem like I commited it sometime. It shouldn't be a Problem to just add them, but I currently don't have them installed so i can't test ist.

**Comment by karaktaka** [comment]
It may be a bit late now, but my newest release does introduce support for wind and rain gauge

**Comment by sweh** [comment]
Thanks, will have a look next week.
